### ISSUE TITLE
Error in app.module.ts with angular 4

### ISSUE THREAD

**Issue by javatechy** [RedFroggy/angular-spring-hmac#11]
I am using the same repo code with angular 4.0.0 .

I am facing problem in app.module.ts. 
Getting this error:
`vendor.bundle.js:57784 Uncaught Error: Can't resolve all parameters for useFactory: (?, ?, ?).
    at syntaxError (http://localhost:4200/vendor.bundle.js:44710:34) [<root>]
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:57558:35) [<root>]
    at CompileMetadataResolver._getFactoryMetadata (http://localhost:4200/vendor.bundle.js:57438:51) [<root>]
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:57709:43) [<root>]
    at http://localhost:4200/vendor.bundle.js:57629:49 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:57592:19) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:57248:50) [<root>]
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:68285:64) [<root>]
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:68244:52) [<root>]
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:68206:21) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5239:25) [<root>]
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5225:21) [<root>]
    at Object.128 (http://localhost:4200/main.bundle.js:33:124) [<root>]`

When i remove  providers content it is working fine. How?

@NgModule({
  imports:        [ HttpModule, RouterModule, BrowserModule, AccountModule, LoginModule, UserModule, UtilsModule, RoutesModule ],
  declarations:   [ AppComponent, Header ],
  bootstrap:      [ AppComponent, Header ],
  providers:      [
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    {
      provide: Http,
      useFactory: (xhrBackend: XHRBackend, requestOptions: RequestOptions, accountEventService: AccountEventsService) => {
        return new HmacHttpClient(xhrBackend, requestOptions, accountEventService);
      },
     deps: [XHRBackend, RequestOptions, AccountEventsService],
      multi: false
    }]
})'

After removing the providers i got this error:
`ERROR ReferenceError: _ is not defined
    at new SecurityToken (securityToken.ts:5)
    at HmacHttpClient.webpackJsonp.285.HmacHttpClient.mapResponse (hmac-http-client.ts:65)
    at SafeSubscriber._next (hmac-http-client.ts:100)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:236)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at XMLHttpRequest.onLoad (http.es5.js:1205)
    at ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.es5.js:4116)
    at ZoneDelegate.invokeTask (zone.js:397)
    at Zone.runTask (zone.js:165)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:460)
defaultErrorLogger @ core.es5.js:1084
ErrorHandler.handleError @ core.es5.js:1144
next @ core.es5.js:4754
schedulerFn @ core.es5.js:3828
SafeSubscriber.__tryOrUnsub @ Subscriber.js:236
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3814
NgZone.triggerError @ core.es5.js:4185
onHandleError @ core.es5.js:4146
ZoneDelegate.handleError @ zone.js:369
Zone.runTask @ zone.js:168
ZoneTask.invoke @ zone.js:460`

**Comment by michaeldesigaud** [comment]
Hi, i've updated angular to version 4. Can you test again and tell me if your problem is still here ?
