### ISSUE TITLE
ntsc -p build script error

### ISSUE THREAD

**Issue by cheese8** [RedFroggy/angular-spring-hmac#15]
Hi, how to fix below error to run up this great demo?
`
➜  angular-spring-hmac git:(master) cd src/main/webapp
➜  webapp git:(master) npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @angular/platform-server@4.1.3 requires a peer of @angular/animations@4.1.3 but none was installed.

added 29 packages in 5.751s
➜  webapp git:(master) ✗ cd -
~/angular-spring-hmac
➜  angular-spring-hmac git:(master) ✗ mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-hmac 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (exec-npm-install) @ spring-hmac ---
npm WARN @angular/platform-server@4.1.3 requires a peer of @angular/animations@4.1.3 but none was installed.

up to date in 0.33s
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (exec-npm-run-tsc) @ spring-hmac ---

> springHmac@1.0.0 build /Users/yin/angular-spring-hmac/src/main/webapp
> ntsc -p ../../../

app/account/account.ts(1,1): error TS6053: File '/Users/yin/angular-spring-hmac/typings/lodash/lodash.d.ts' not found.
app/account/account.ts(10,13): error TS2304: Cannot find name '_'.
app/security/securityToken.ts(5,9): error TS2304: Cannot find name '_'.
app/utils/hmac-http-client.ts(40,63): error TS2304: Cannot find name 'CryptoJS'.
app/utils/hmac-http-client.ts(42,63): error TS2304: Cannot find name 'CryptoJS'.
app/utils/hmac-http-client.ts(44,63): error TS2304: Cannot find name 'CryptoJS'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! springHmac@1.0.0 build: `ntsc -p ../../../`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the springHmac@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yin/.npm/_logs/2017-09-27T23_45_42_478Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.594 s
[INFO] Finished at: 2017-09-28T07:45:42+08:00
[INFO] Final Memory: 18M/227M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (exec-npm-run-tsc) on project spring-hmac: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

**Comment by rsachin** [comment]
I am also experiencing the same issue. Please suggest the fix.

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building spring-hmac 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) > test-compile @ spring-hmac >>>
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (exec-npm-install) @ spring-hmac ---
npm WARN @angular/platform-server@4.1.3 requires a peer of @angular/animations@4.1.3 but none was installed.
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (exec-npm-run-tsc) @ spring-hmac ---

> springHmac@1.0.0 build C:\practice\code\previous\angular-spring-hmac-master\src\main\webapp
> ntsc -p C:\practice\code\previous\angular-spring-hmac-master

app/account/account.ts(1,1): error TS6053: File 'C:/practice/code/previous/angular-spring-hmac-master/typings/lodash/lodash.d.ts' not found.
app/account/account.ts(10,13): error TS2304: Cannot find name '_'.
app/security/securityToken.ts(5,9): error TS2304: Cannot find name '_'.
app/utils/hmac-http-client.ts(40,63): error TS2304: Cannot find name 'CryptoJS'.
app/utils/hmac-http-client.ts(42,63): error TS2304: Cannot find name 'CryptoJS'.
app/utils/hmac-http-client.ts(44,63): error TS2304: Cannot find name 'CryptoJS'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\practice\\sysprograms\\node-v6.11.3-win-x64\\node.exe" "C:\\practice\\sysprograms\\node-v6.11.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! springHmac@1.0.0 build: `ntsc -p C:\practice\code\previous\angular-spring-hmac-master`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the springHmac@1.0.0 build script 'ntsc -p C:\practice\code\previous\angular-spring-hmac-master'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the springHmac package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ntsc -p C:\practice\code\previous\angular-spring-hmac-master
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs springHmac
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls springHmac
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\practice\code\previous\angular-spring-hmac-master\src\main\webapp\npm-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

**Comment by michaeldesigaud** [comment]
The problem should be solved
